name: auth_repo
description: Dart package which manages the backend domain.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.4
dev_dependencies: 
  flutter_lints: ^1.0.4

  